# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='city',
            field=models.CharField(default='yangming is here', max_length=80),
        ),
        migrations.AlterField(
            model_name='reading',
            name='location',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='reading',
            name='weather',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='reading',
            name='wind',
            field=models.CharField(max_length=1000),
        ),
    ]
